apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-eso
  annotations:
    azure.workload.identity/client-id: 8cc3449b-3c69-4edb-a236-27eedf2381ee # SP Loki
    azure.workload.identity/tenant-id: dc1d2d98-eccf-4852-92b3-130cb1192b60
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: loki
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-loki-iprd-ue.vault.azure.net/"
      serviceAccountRef:
        name: loki-eso
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: loki
  target:
    name: loki-storage
    creationPolicy: Owner
  data:
    - secretKey: ACCOUNT_NAME
      remoteRef:
        key: secret/Storage--AccountName
    - secretKey: ACCOUNT_KEY
      remoteRef:
        key: secret/Storage--PrimaryAccessKey
    - secretKey: CONTAINER_NAME
      remoteRef:
        key: secret/Storage--ContainerName

