apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets.yml
  # - loki-grafana-datasource.configmap.yml
helmCharts:
  - name: loki-distributed
    repo: https://grafana.github.io/helm-charts
    version: 0.67.1
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yml
      
