apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
  # - loki-grafana-datasource.configmap.yml
#   - thanos-external-secrets.yml
#   - grafana-datasource.yml
helmCharts:
  - name: loki-distributed
    repo: https://grafana.github.io/helm-charts
    version: 0.67.1
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yml
  # - name: loki-stack
  #   repo: https://grafana.github.io/helm-charts
  #   version: 2.8.9
  #   releaseName: loki-stack
  #   namespace: monitoring
  #   valuesFile: loki-stack-values.yml
      
