apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-stack
  labels:
    grafana_datasource: '1'
data:
  loki-stack-datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki-loki-distributed-query-frontend:3100"
      version: 1
      isDefault: true
      jsonData:
        {}
