apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    # database owner
    dba:
    - superuser
    - createdb

    # role for application foo
    foo_user: [] # or 'foo_user: []'

  #databases: name->owner
  databases:
    foo: dba
  postgresql:
    version: "14"