apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-sidecar-eso
  annotations:
    azure.workload.identity/client-id: 5d4cb1c3-fbeb-4bd7-98f9-a0f6c319f7b2 # SP Thanos
    azure.workload.identity/tenant-id: dc1d2d98-eccf-4852-92b3-130cb1192b60
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: thanos-sidecar
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-thanos-iprd-ue.vault.azure.net/"
      serviceAccountRef:
        name: thanos-sidecar-eso
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-sidecar
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: thanos-sidecar
  target:
    name: thanos-sidecar-objstore-config
    creationPolicy: Owner
  data:
    - secretKey: thanos.yml
      remoteRef:
        key: secret/thanos-yml
