apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-eso
  annotations:
    azure.workload.identity/client-id: 4ba37dd5-4e20-48a5-9f59-5b8c9e083367 # SP grafana
    azure.workload.identity/tenant-id: dc1d2d98-eccf-4852-92b3-130cb1192b60
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: grafana-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-grafana-iprd-ue.vault.azure.net/"
      serviceAccountRef:
        name: grafana-eso
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: grafana-secret-store
  target:
    name: azure-auth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: secret/ClientId    
    - secretKey: client_secret
      remoteRef:
        key: secret/ClientSecret
    - secretKey: auth_url
      remoteRef:
        key: secret/AuthUrl
    - secretKey: token_url
      remoteRef:
        key: secret/TokenUrl