apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yml
  - external-secrets.yml
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: "6.48.*"
    releaseName: grafana
    namespace: monitoring
    valuesFile: values.yml
