apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
  # - loki-grafana-datasource.configmap.yml
#   - thanos-external-secrets.yml
#   - grafana-datasource.yml
helmCharts:
  - name: fluent-bit
    repo: https://grafana.github.io/helm-charts
    version: 2.3.2
    releaseName: fluent-bit
    namespace: monitoring
    valuesFile: values.yml
      
