## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
  # https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        Multiline.Parser cri

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  # https://docs.fluentbit.io/manual/pipeline/filters
  filters: |

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  # [FILTER]
  #     Name parser
  #     Match kube.*
  #     Key_Name message
  #     Parser logfmt
  #     Preserve_Key On
  #     Reserve_Data On


  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        name loki
        match *
        host loki-loki-distributed-distributor
        port 3100
        labels job=fluent-bit
        auto_kubernetes_labels off
        line_format json
        label_map_path /fluent-bit/etc/kubernetes.map.json

#remove_keys kubernetes,stream
  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name logfmt      
        Format logfmt
        
  # [PARSER]
  #     Name        cri
  #     Format      regex
  #     Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
  #     Time_Key    time
  #     Time_Format %Y-%m-%dT%H:%M:%S.%L%z
  
  extraFiles:
    kubernetes.map.json: |-
      {
        "kubernetes": {     
          "host": "node",     
          "namespace_name": "namespace",
          "pod_name": "pod",
          "container_name": "container",
          "container_image": "container_image",
          "labels": {
            "app.kubernetes.io/name": "app"
          },
          "namespace_name": "namespace"
        },
        "stream": "stream"
      }