apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  thanos-datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Thanos
      type: prometheus
      uid: thanos
      url: http://thanos-query:9090
      access: proxy
      isDefault: false
      jsonData:
        timeInterval: 30s
