apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thanos-external-secrets.yml
  - grafana-datasource.yml
helmCharts:
  - name: thanos
    repo: https://charts.bitnami.com/bitnami
    version: 11.6.5
    releaseName: thanos
    namespace: monitoring
    valuesFile: values.yml
      
